"""Add settings model

Revision ID: da074198407f
Revises: da589ea66408
Create Date: 2025-06-12 17:00:46.724426

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da074198407f'
down_revision = 'da589ea66408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=128), nullable=True),
    sa.Column('university', sa.String(length=128), nullable=True),
    sa.Column('major', sa.String(length=128), nullable=True),
    sa.Column('grad_year', sa.String(length=8), nullable=True),
    sa.Column('task_reminders', sa.Boolean(), nullable=True),
    sa.Column('habit_reminders', sa.Boolean(), nullable=True),
    sa.Column('devotion_reminders', sa.Boolean(), nullable=True),
    sa.Column('calendar_notifications', sa.Boolean(), nullable=True),
    sa.Column('reminder_time', sa.String(length=16), nullable=True),
    sa.Column('theme', sa.String(length=16), nullable=True),
    sa.Column('accent_color', sa.String(length=8), nullable=True),
    sa.Column('compact_mode', sa.Boolean(), nullable=True),
    sa.Column('animations', sa.Boolean(), nullable=True),
    sa.Column('gpa_scale', sa.String(length=8), nullable=True),
    sa.Column('default_task_category', sa.String(length=32), nullable=True),
    sa.Column('week_start', sa.String(length=8), nullable=True),
    sa.Column('show_gpa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('tasks')

    with op.batch_alter_table('project_activity', schema=None) as batch_op:
        batch_op.alter_column('user_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('project_activity_project_id_fkey'), type_='foreignkey')

    with op.batch_alter_table('project_invitation', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('invited_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('project_invitation_project_id_fkey'), type_='foreignkey')

    with op.batch_alter_table('project_member', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('project_member_project_id_fkey'), type_='foreignkey')

    with op.batch_alter_table('task_comment', schema=None) as batch_op:
        batch_op.alter_column('author_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('task_comment_task_id_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_comment', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('task_comment_task_id_fkey'), 'task', ['task_id'], ['id'])
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('author_email',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('project_member', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('project_member_project_id_fkey'), 'project', ['project_id'], ['id'])
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('project_invitation', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('project_invitation_project_id_fkey'), 'project', ['project_id'], ['id'])
        batch_op.alter_column('invited_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('project_activity', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('project_activity_project_id_fkey'), 'project', ['project_id'], ['id'])
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('user_email',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tasks', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))

    op.drop_table('settings')
    # ### end Alembic commands ###
